### ISSUE TITLE
Uploading track loses current tracks until refresh

### ISSUE THREAD

**Issue by zsmoore** [ryanthomas30/AudioNimbus#58]
I went to a test profile not owned by me and uploaded my own audio file while I was on the other profile's about.
When I went back to the audio page there were no more tracks anymore even though there originally were.

A refresh fixed the issue.

**Comment by ryanthomas30** [comment]
The tracks disappearing is not new. The quick-fix was to force a reload. Not sure why that didn't happen here.

**Comment by zsmoore** [comment]
Actually I didn't realize my upload failed because I did not put an image so it wasn't actually caused by a full upload rather just an attempt.

Is your force refresh called upon a successful upload?

**Comment by ryanthomas30** [comment]
Ah yes, this is addressed in #31. 

It is in fact only called upon a successful upload.
