### ISSUE TITLE
Bug:The searching isn't working

### ISSUE THREAD

**Issue by QinxinTian** [ryanthomas30/AudioNimbus#65]
[Screen Capture 28.mov.zip](https://github.com/ryanthomas30/AudioNimbus/files/1446059/Screen.Capture.28.mov.zip)
[Screen Capture 29.mov.zip](https://github.com/ryanthomas30/AudioNimbus/files/1446073/Screen.Capture.29.mov.zip)
No matter if it is before or after log in, the searching isn't working.

**Comment by ryanthomas30** [comment]
The search feature is currently not implemented. Addressed by #28
